FORMAT: 1A

# Mirmidon API
Documentation Mirmidon API.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

# Group Mirmidon-unstable
Resources of the **Mirmidon-unstable API**

# Mirmidon API Root [/]
Point d'entrée de l'API.

Cette ressource n'a aucun attribut.

## Retrieve the Entry Point [GET]

+ Response 200 (application/json)
    + Headers
    
            "Accept":"application/json",
            "Content-Type":"application/json"

    + Body

            {
                
            }

## Fieldsite [/explorer/fieldsite]
L'objet fieldsite

Cette ressource dispose des attributs suivants: 

- id
- name
- creationdate

Le champ *id* et  *created_at* sont assignés par l'API au moment de la création de la ressource. 


+ Model (application/json)

    Représentation JSON de la ressource. Veuillez noter que la ressource est elle-même contenu dans le champ "data" de la réponse.

    + Body

            {
                "id": 1,
                "name": "Taiwan",
                "creationDate": "2014-11-04 12:21:26.999"
            }

### Récupération de la liste des fieldsites [GET]
+ Response 200
    
### Suppression d'un fieldsite [DELETE]
+ Response 204

### Création d'un fieldsite [POST]
Pour créer un fieldsite, fournir simplement le champ *name* du nouveau fieldsite. 

+ Request (application/json)

        {
            "name": "Taiwan"
        }

+ Response 201

    [Fieldsite][]
    
