FORMAT: 1A

# Mirmidon
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Fieldsites
Notes related resources of the **Mirmidon API**



## Note [/notes/{id}/{token}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.
    + token (required, string, `foo` ) ... Test.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204

### Update a Note [PUT]
+ Response 200 (application/json)

    + Body
    
            { "id": 2, "title": " Updated title" }