FORMAT: 1A
HOST: http://p4x-650.gateworld.fr:9082

# Mirmidon API
Documentation Mirmidon API.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

# Group Fieldsites
Gestion des fieldsites de **Mirmidon-unstable API**

# Base [/]
Point d'entrée de l'API.

Cette ressource n'a aucun attribut.
+ Response 200
    +Headers
    
            Accept:application/json,
            Content-Type:application/json

## Lister les fieldsites [/explorer/fieldsite/list]

    Note: Should be an HTTP GET

### POST

+ Response 200
    + Headers
    
            Accept:application/json,
            Content-Type:application/json

    + Body
    
            [{
               "data":
               {
                   "0":
                   {
                       "id": 1,
                       "name": "Taiwan",
                       "creationDate": "2014-11-04 12:21:26.999"
                   },
                    "0":
                   {
                       "id": 2,
                       "name": "Fieldsite2",
                       "creationDate": "2014-11-04 12:24:22.548"
                   },
                   ... More ...
               },
               "code": 0,
               "message": ""
            }]

 
## Ajouter un fieldsite [/explorer/fieldsite/add]
Pour créer un fieldsite, fournir simplement le champ `name` du nouveau fieldsite. 

### POST

+ Request (application/json)

        [{
            "name": "Taiwan"
        }]


+ Response 200
    + Headers
    
            Accept:application/json,
            Content-Type:application/json

    + Body

            [{
                "code": 0,
                "message": null,
                "data":
                    {
                        "id": 2,
                        "name": "SaintJean",
                        "creationDate": "2014-11-04 12:21:26.999"
                    }
            }]
            

## Supprimer un fieldsite [/explorer/fieldsite/remove]
### POST

    Donner l'ID du fieldsite à supprimer dans le champ 'data'
    
+ Request (application/json)


        [{
            "data": 3
        }]

+ Response 200

    + Body
    
            [{
                "code":0,
                "message":null,
                "data":null
            }]

+ Response 500

    **Attention, normalement le code HTTP devrait être différent de 200, la réponse en cas d'erreur est correcte mais pas le code qui reste à 200**

    + Body
    
            [{
                "code": 2,
                "message": "Impossible to find speficied fieldsite",
                "data": null
            }]



# Group Explorer
Explorer de **Mirmidon-unstable API**

    More to come...