# Group Explorer
Explorer de **Mirmidon-unstable API**

## Phenomena list [/explorer/phenomena/list]
    ERREUR: API en erreur @todo : documenter dès correction.

### GET

+ Response 200
    + Headers

            Content-Type:text/html; charset=utf-8

    + Body

            {  
                "data":{  
                    "phenomenon":{  
                        "0":{  
                            "standard_name":"pressure",
                            "variables":{  
                                "0":{  
                                    "standard_name":"pressure",
                                    "unit":"",
                                    "type":"PhenomenaVariable",
                                    "data_type":"double",
                                    "minimum_value":0.0,
                                    "maximun_value":1.0,
                                    "fill_value":"NaN",
                                    "scale":1.0,
                                    "offset":0.0,
                                    "units":{  
                                        "0":"Pa",
                                        "1":"hPa",
                                        "2":"kPa"
                                    }
                                }
                            }
                        },
                        "1":{  
                            "standard_name":"wind",
                            "variables":{  
                                "0":{  
                                    "standard_name":"u",
                                    "unit":"",
                                    "type":"PhenomenaVariable",
                                    "data_type":"double",
                                    "minimum_value":0.0,
                                    "maximun_value":1.0,
                                    "fill_value":"NaN",
                                    "scale":1.0,
                                    "offset":0.0,
                                    "units":{  
                                        "0":"m/s",
                                        "1":"deg",
                                        "2":"km/h",
                                        "3":"rad"
                                    }
                                },
                                "1":{  
                                    "standard_name":"v",
                                    "unit":"",
                                    "type":"PhenomenaVariable",
                                    "data_type":"double",
                                    "minimum_value":0.0,
                                    "maximun_value":1.0,
                                    "fill_value":"NaN",
                                    "scale":1.0,
                                    "offset":0.0,
                                    "units":{  
                                        "0":"m/s",
                                        "1":"deg",
                                        "2":"km/h",
                                        "3":"rad"
                                    }
                                }
                            }
                        },
                        "2":{  
                            "standard_name":"current",
                            "variables":{  
                                "0":{  
                                    "standard_name":"u",
                                    "unit":"",
                                    "type":"PhenomenaVariable",
                                    "data_type":"double",
                                    "minimum_value":0.0,
                                    "maximun_value":1.0,
                                    "fill_value":"NaN",
                                    "scale":1.0,
                                    "offset":0.0,
                                    "units":{  
                                        "0":"m/s"
                                    }
                                },
                                "1":{  
                                    "standard_name":"v",
                                    "unit":"",
                                    "type":"PhenomenaVariable",
                                    "data_type":"double",
                                    "minimum_value":0.0,
                                    "maximun_value":1.0,
                                    "fill_value":"NaN",
                                    "scale":1.0,
                                    "offset":0.0,
                                    "units":{  
                                        "0":"m/s"
                                    }
                                }
                            }
                        },
                        "3":{  
                            "standard_name":"bathymetry",
                            "variables":{  
                                "0":{  
                                    "standard_name":"z",
                                    "unit":"",
                                    "type":"PhenomenaVariable",
                                    "data_type":"double",
                                    "minimum_value":0.0,
                                    "maximun_value":1.0,
                                    "fill_value":"NaN",
                                    "scale":1.0,
                                    "offset":0.0,
                                    "units":{  
                                        "0":"m"
                                    }
                                }
                            }
                        },
                        "4":{  
                            "standard_name":"tide",
                            "variables":{  
            
                            }
                        },
                        "5":{  
                            "standard_name":"hs",
                            "variables":{  
                                "0":{  
                                    "standard_name":"hs",
                                    "unit":"",
                                    "type":"PhenomenaVariable",
                                    "data_type":"double",
                                    "minimum_value":0.0,
                                    "maximun_value":1.0,
                                    "fill_value":"NaN",
                                    "scale":1.0,
                                    "offset":0.0,
                                    "units":{  
                                        "0":"m"
                                    }
                                }
                            }
                        }
                    },
                    "type":"Phenomenon",
                    "id":"Phenomenon",
                    "abstract":"Phenomenon"
                },
                "code":0,
                "message":""
            }

## Phenomena ASCII list [/explorer/phenomena/ascii/list]

### GET

+ Response 200
    + Headers

            Content-Type:application/json

    + Body

            {  
                "phenomenon":{  
                    "0":{  
                        "standard_name":"pressure",
                        "variables":{  
                            "0":{  
                                "standard_name":"pressure",
                                "unit":"",
                                "type":"ASCIIPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"Pa",
                                    "1":"hPa",
                                    "2":"kPa"
                                },
                                "column":-1
                            }
                        }
                    },
                    "1":{  
                        "standard_name":"wind",
                        "variables":{  
                            "0":{  
                                "standard_name":"u",
                                "unit":"",
                                "type":"ASCIIPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m/s",
                                    "1":"deg",
                                    "2":"km/h",
                                    "3":"rad"
                                },
                                "column":-1
                            },
                            "1":{  
                                "standard_name":"v",
                                "unit":"",
                                "type":"ASCIIPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m/s",
                                    "1":"deg",
                                    "2":"km/h",
                                    "3":"rad"
                                },
                                "column":-1
                            }
                        }
                    },
                    "2":{  
                        "standard_name":"current",
                        "variables":{  
                            "0":{  
                                "standard_name":"u",
                                "unit":"",
                                "type":"ASCIIPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m/s"
                                },
                                "column":-1
                            },
                            "1":{  
                                "standard_name":"v",
                                "unit":"",
                                "type":"ASCIIPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m/s"
                                },
                                "column":-1
                            }
                        }
                    },
                    "3":{  
                        "standard_name":"bathymetry",
                        "variables":{  
                            "0":{  
                                "standard_name":"z",
                                "unit":"",
                                "type":"ASCIIPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m"
                                },
                                "column":-1
                            }
                        }
                    },
                    "4":{  
                        "standard_name":"tide",
                        "variables":{  

                        }
                    },
                    "5":{  
                        "standard_name":"hs",
                        "variables":{  
                            "0":{  
                                "standard_name":"hs",
                                "unit":"",
                                "type":"ASCIIPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m"
                                },
                                "column":-1
                            }
                        }
                    }
                },
                "type":"Phenomenon",
                "id":"Phenomenon",
                "abstract":"Phenomenon"
            }

## Phenonema NetCDF list [/explorer/phenomena/netcdf/list]

### GET

+ Response 200
    + Headers

            Content-Type:application/json

    + Body

            {  
                "phenomenon":{  
                    "0":{  
                        "standard_name":"pressure",
                        "variables":{  
                            "0":{  
                                "standard_name":"pressure",
                                "unit":"",
                                "type":"NetcdfPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"Pa",
                                    "1":"hPa",
                                    "2":"kPa"
                                },
                                "netcdf_variable_name":""
                            }
                        }
                    },
                    "1":{  
                        "standard_name":"wind",
                        "variables":{  
                            "0":{  
                                "standard_name":"u",
                                "unit":"",
                                "type":"NetcdfPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m/s",
                                    "1":"deg",
                                    "2":"km/h",
                                    "3":"rad"
                                },
                                "netcdf_variable_name":""
                            },
                            "1":{  
                                "standard_name":"v",
                                "unit":"",
                                "type":"NetcdfPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m/s",
                                    "1":"deg",
                                    "2":"km/h",
                                    "3":"rad"
                                },
                                "netcdf_variable_name":""
                            }
                        }
                    },
                    "2":{  
                        "standard_name":"current",
                        "variables":{  
                            "0":{  
                                "standard_name":"u",
                                "unit":"",
                                "type":"NetcdfPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m/s"
                                },
                                "netcdf_variable_name":""
                            },
                            "1":{  
                                "standard_name":"v",
                                "unit":"",
                                "type":"NetcdfPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m/s"
                                },
                                "netcdf_variable_name":""
                            }
                        }
                    },
                    "3":{  
                        "standard_name":"bathymetry",
                        "variables":{  
                            "0":{  
                                "standard_name":"z",
                                "unit":"",
                                "type":"NetcdfPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m"
                                },
                                "netcdf_variable_name":""
                            }
                        }
                    },
                    "4":{  
                        "standard_name":"tide",
                        "variables":{  
            
                        }
                    },
                    "5":{  
                        "standard_name":"hs",
                        "variables":{  
                            "0":{  
                                "standard_name":"hs",
                                "unit":"",
                                "type":"NetcdfPhenomenaVariable",
                                "data_type":"double",
                                "minimum_value":0.0,
                                "maximun_value":1.0,
                                "fill_value":"NaN",
                                "scale":1.0,
                                "offset":0.0,
                                "units":{  
                                    "0":"m"
                                },
                                "netcdf_variable_name":""
                            }
                        }
                    }
                },
                "type":"Phenomenon",
                "id":"Phenomenon",
                "abstract":"Phenomenon"
            }

## Phenomena list by Fieldset [/explorer/phenomena/by-fieldsite?id={id}]

### GET

+ Parameters

    + id = `` (required, integer, `1`) ... Fieldsite Identifier.

+ Response 200
    + Headers

            Content-Type:application/json

    + Body

            {

            "data": {
                    "phenomenon": {
                                    "0":{
                                            "standard_name": "pressure",
                                            "variables": {
                                            "0": {
                                                    "standard_name": "pressure",
                                                    "unit": "",
                                                    "type": "PhenomenaVariable",
                                                    "data_type": "double",
                                                    "minimum_value": 0,
                                                    "maximun_value": 1,
                                                    "fill_value": "NaN",
                                                    "scale": 1,
                                                    "offset": 0,
                                                    "units": 
                                                        {
                                                            "0": "Pa",
                                                            "1": "hPa",
                                                            "2": "kPa"
                                                        }
                                                    },
                                                    //Cut example, there can be more variables
                                            }
                                        },
                                        //Cut example, there can be more phenomenon
                                    }
                    }

            }

## Phenomena Info [/explorer/phenomena/info?standardName={standardName}]
Item not documented 

### GET

+ Parameters

    + standardName = `` (required, string, `Test`) ... Phenomena standard name.

+ Response 200

    + Headers

            Content-Type:application/json

    + Body

            {  
                "code":7,
                "message":"Phenomena with standard name Test wasn't found.",
                "data":null
            }

## Phenomena Plot [/explorer/phenomena/plot?id={id}]
Item not documented 

### GET

+ Parameters

    + id = `` (required, integer, `1`) ... @todo: document.

+ Response 200

    + Headers

            Content-Type:application/json

    + Body

            {  
                "data":"",
                "code":2,
                "message":"None aggregation with this id"
            }

## List coordinate reference system [/explorer/coordinate-reference-system/list]
Item not documented - High load time.

### GET
+ Response 200
    + Headers

            Content-Type:application/json

    + Body

            {  
                "data":{  
                    "0":{  
                        "id":"CRS:84",
                        "name":"WGS84",
                        "remarks":"",
                        "scope":""
                    },
                    "1":{  
                        "id":"EPSG:4326",
                        "name":"WGS 84",
                        "remarks":"",
                        "scope":"Horizontal component of 3D system. Used by the GPS satellite navigation system and for NATO military geodetic surveying."
                    },
                    "2":{  
                        "id":"EPSG:2154",
                        "name":"RGF93 / Lambert-93",
                        "remarks":"",
                        "scope":"Large and medium scale topographic mapping and engineering survey."
                    }
                },
                "code":0,
                "message":""
            }

## List aggregations [/explorer/maggregation/list]
Item not documented - Should be rewritten when the aggregator is working (output empty list)

### GET

+ Response 200

    + Headers

            Content-Type:application/json

    + Body

            {  
                "data":{  
                    "aggreations":{  
                        //Shouldn't be empty
                    }
                },
                "code":0,
                "message":""
            }

## List aggregations by phenomenon [/explorer/maggregation/by-phenomenon?idFieldSite={idFieldSite}&idPhenomenon={idPhenomenon}]
Item not documented - Should be rewritten when the aggregator is working (output empty list)

### GET

+ Parameters

    + idFieldSite = `` (required, integer, `1`) ... Fieldsite ID.
    + idPhenomenon = `` (required, integer, `1`) ... Phenomenon ID.

+ Response 200

    + Headers

            Content-Type:application/json

    + Body

            {  
                "code":0,
                "message":null,
                "data":{  
                    //Shouldn't be empty
                }
            }

## Media -?- [/explorer/media?token={token}]
Item not documented and probably deprecated?

### GET

+ Parameters

    + token = `` (required, string, `unknown`) ... A media token (who gives it?).

+ Response 200

    + Headers

            Content-Type:application/json

    + Body

            Execution exception
            [NullPointerException: null]
            In /data/MIRMIDON/unstable/mirmidon/LOGIC/app/controllers/m_explorer/ExplorerManager.java at line 19.

