FORMAT: 1A
HOST: http://p4x-650.gateworld.fr:9082

# Mirmidon API
Documentation Mirmidon API.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.
